---
# Docker instalation on EC2 amazon OS

- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - git
      - python3
      - python3-pip
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - amazon-linux-extras

- name: Add extras repository
  shell: yum-config-manager --enable extras

- name: Install docker-ce (centos) via amazon-linux-extras packages
  shell: "amazon-linux-extras install docker=18.06.1 -y"

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure Python pip packages are installed
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
      - docker-compose