all:
  children:
    aws_vms:
      children:
        elk_stack:
          hosts:
            elk_host:
              ansible_host: 3.136.17.5  # <-- change this IP
        py_app:
          hosts:
            echo_service:
              ansible_host: 3.135.201.107 # <-- change this IP