all:
  children:
    aws_vms:
      children:
        elk_stack:
          hosts:
            elk_host:
              ansible_host: 52.14.197.49  # <-- change this IP
        py_app:
          hosts:
            echo_service:
              ansible_host: 3.129.24.14 # <-- change this IP
