all:
  children:
    aws_vms:
      children:
        elk_stack:
          hosts:
            elk_host:
              ansible_host: 18.224.65.210  # <-- change this IP
        py_app:
          hosts:
            echo_service:
              ansible_host: 3.17.156.75 # <-- change this IP
