---
  # This Playbool would setup ec2 server

- name: Setup EC2 instances
  hosts: all
  become: true
  remote_user: "{{ default_user }}"
  roles:
    - setup_ec2
    - weareinteractive.environment
  vars:
    environment_config:
      ELK_VERSION: 7.8.0  # ELK stack version
