version: '3.8'

services:
  elasticsearch:
    build: 
      context: ./elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      ELASTIC_PASSWORD: admin
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
    ports:
      - "9200:9200"
      - "9300:9300"
  
  logstash:
    build:
      context: ./logstash
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ES_USERNAME: "elastic"
      ES_PASSWORD: "admin"
      FB_TCP_PORT: "5044"
    volumes:
      - "./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro"
      - "./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
    ports:
      - "5044:5044/tcp"
      - "5044:5044/udp"
      - "9600:9600/tcp"
      - "9600:9600/udp"
    depends_on:
      - elasticsearch
  
  kibana:
    build:
      context: ./kibana
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      ES_USERNAME: "elastic"
      ES_PASSWORD: "admin"
    volumes:
      - "./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
